name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install -y libbpfcc-dev
      - name: Build
        run: go build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: tracecap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
